# Generated by Django 5.2.7 on 2026-01-04 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[('desmatamento', 'Desmatamento'), ('queimada', 'Queimada'), ('poluicao', 'Poluição'), ('caca', 'Caça Ilegal'), ('outro', 'Outro')], max_length=50)),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('data_ocorrencia', models.DateField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='denuncias/anexos/')),
                ('anonima', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Em análise', 'Em análise'), ('Resolvida', 'Resolvida'), ('Não verificada', 'Não verificada')], default='Em análise', max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Denunciante')),
            ],
            options={
                'verbose_name': 'Denúncia',
                'verbose_name_plural': 'Denúncias',
                'ordering': ['-data_registro'],
            },
        ),
    ]
